---

response:
  type: object
  properties:
    count: 
      type: integer
      required: true
    newest_id: 
      type: integer
      required: true
    oldest_id: 
      type: integer
      required: true
    next_token: 
      type: string
    previous_token:
      type: string
