[package]
name = "oauth-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.16"
once_cell = "1.17.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tower-cookies = { version = "0.9.0", features = ["private"] }
twapi-v2 = { path="../..", features = ["retry", "oauth"] }
url = "2.3.1"

[features]
retry = []
oauth = []