name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: CONSUMER_KEY=${{ secrets.CONSUMER_KEY }} CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }} ACCESS_KEY=${{ secrets.ACCESS_KEY }} ACCESS_SECRET=${{ secrets.ACCESS_SECRET }} cargo test test_get_2_tweets_id_oauth --all-features -- --nocapture --test-threads=1
